#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"cargo:cargo-insta" = "1.42.2"
"cargo:cargo-nextest" = "0.9.93"
rust = "1.84"
uv = "0.5.1"

[tasks."format"]
description = "Format the code"
tools.rust = "nightly"
run = "cargo fmt"

[tasks."lint"]
description = "Lint the code"
run = "cargo clippy --workspace --all-targets"

[tasks."zizmor"]
description = "Check GitHub workflows with Zizmor"
run = "uvx zizmor ."

[tasks."test"]
description = "Run tests"
run = "cargo insta test --workspace --test-runner nextest"

[tasks."update-cli-help"]
description = "Update generated CLI help (cli/tests/cli-reference@.md.snap)"
run = "cargo insta test --accept --workspace -- test_generate_md_cli_help"

[tasks."docs:build"]
description = "Build documentation into rendered-docs/ for offline use"
run = "uv run mkdocs build -f mkdocs-offline.yml"

[tasks."docs:serve"]
description = "Preview documentation with live reloading"
run = "uv run mkdocs serve"
