name: docs-preview-cleanup

permissions:
  contents: write

on:
  # This always uses the workflow file from the main branch
  pull_request_target:
    types: [closed]
    

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - run: echo "bad"
